server:
  port: 80
  servlet:
    session:
      timeout: 3600s
spring:
  application:
    name: 90foodmall
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/90foodmall?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT
    username: root
    password: 123456
    hikari:
      minimum-idle: 3
      maximum-pool-size: 10
      max-lifetime: 3000
  redis:
    host: localhost
    port: 6379
    jedis:
      pool:
        max-active: 30 #连接池最大连接数（使用负值表示没有限制）
        max-wait: 10000 #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 30 #连接池中的最大空闲连接
        min-idle: 10 #连接池中的最小空闲连接
    timeout: 30000 #连接超时时间（毫秒）
  mail:
    host: smtp.qq.com
    username: 
    password: 
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  data:
    elasticsearch:
      cluster-nodes: localhost:9300 # es的连接地址及端口号
      cluster-name: my-application # es集群的名称
mybatis-plus:
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0
      table-underline: true
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#全局参数
user:
  loginPassword: 123456
  payPassword: 123456
TOKEN_EXPIRE: 1800
